### ISSUE TITLE
If User Mis-clicks When Attempting to Remove a User - There is No Way to Go Back to Choose Again

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1241] opened 2022-11-15 02:28 UTC
Overview
When attempting to remove a user, if the users misses the remove button and clicks on another option, they will need to go back to the beginning to search for the product managers name again in order to locate the individual, then click on their name in order to get back to the remove button versus just hitting a back button to remove more quickly.  Essentially the user has to repeat the workflow again to get back to the correct screen to complete the task.  

Action Items
- [x] UX/UI to consider user flow and design for back button or method to return back to the previous page to remove a user
- [x] UX/UI to share parameters with the dev team to implement

Acceptance Criteria
GIVEN that the user has the ability to remove PMs from a project
WHEN they go to remove a volunteer from a project, if they mis-click and need to go back one step
THEN the user should easily see a back button or method to quickly return to the previous screen to complete the task; no matter what option they choose 

Resources/Instructions
Zoom time stamp [16:10]
Zoom recording - https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq

If the users misses this remove button:
![Picture1](https://user-images.githubusercontent.com/113402837/201810443-6e8b317f-a730-4c48-855d-75d812dd95e2.png)

Then there is nowhere to go at the next screen after selecting admin dashboard to return back to the previous screen.  No matter what choice is selected, the user should be able to return to that previous screen.

![image](https://user-images.githubusercontent.com/113402837/201810735-241fe492-d9b1-410a-86f3-b339aee83d97.png)

Because there was no back button Bonnie had to go back to User Management – retype David’s name to find him again, click on his name and then click the remove button from there to complete the task.

**Comment by JudyLee533** [comment] 2023-01-30 15:52
### Existing user flow 
<img width="3166" alt="Issue 1241 with Annotations (Current)" src="https://user-images.githubusercontent.com/107373945/215525909-a3ab7665-009f-4b31-b17d-5e59d7634a3d.png">

**Dev Team to use as reference**

**Comment by JudyLee533** [comment] 2023-01-30 15:53
### New user flow
<img width="3053" alt="Issue 1241 with Annotations (Updated)" src="https://user-images.githubusercontent.com/107373945/215526057-9b46ea4a-0e4b-4d5a-b25b-6b7c18e1e5ff.png">

**Dev Team to review new flow.**

**Comment by MattPereira** [comment] 2023-02-27 21:44
@heyitsalexander @AmandaGlover-PM @juliagab56 

I have not worked on this issue because I talked to Bonnie and we agreed that it would be better for her to test and approve the new user flow before devs start implementing it with code

I also think it might be a good idea to consider more clearly defining how we hand off issues from design to development

My proposal ( open to however you want to handle this ) :
1. Closing out UI/UX issues when they are finished to separate design issues from development 
2. Have a UX or PM lead leave a comment at end of design issues as they are closed explaining the situation like "We tested this with the stakeholder and she approved, this is now ready to be decomposed into issues for developers"
3. And then add a `ready for dev lead` label and move the closed issue into the `New Issue Approval` column in order to communicate that the issue is ready for developers to start creating new issues to implement these beautiful designs

That way the action items of an issue won't already be checked off and can be tailored to the steps that need to be taken by developers to implement the code

Also it would be really helpful if there are figma links that could be included in addition to the screenshots

**Comment by JackHaeg** [comment] 2023-09-08 01:21
Add page history interaction so that back button returns to previous search states.

**Comment by bkmorgan3** [comment] 2023-11-07 16:56
@jbubar Would design or requirements for this ticket need to be updated?  I don't have the same UI flow as shown in the video and want make sure scope is accurate.

**Comment by JackHaeg** [comment] 2023-11-13 22:09
@bkmorgan3 This is no longer an issue and can be closed. (user can no longer click on "Admin Dashboard" as one of the options, and will remain on the User page when removing them from projects).

**Closed as completed by JackHaeg** 2023-11-13 22:09 UTC
Labels: p-feature: Navigation, Epic/Overview, size: 0.5pt, role: Dev Lead, complexity: missing
