### ISSUE TITLE
As a HforLA admin, I need to be able to assign a lead PM to be able to assign admin permission to other project PMs

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1273] opened 2023-01-24 03:19 UTC
### Overview
Currently, only Bonnie has the ability to elevate and change permission levels for different user. This has historically been changed on the backend. We need to give Bonnie, an interface where she can make those changes on the frontend.

This way, we can change user levels for different volunteers so that they can change the meeting time for their projects.

### Resources

- #1243
- #1534 This issue defines what users will have what permissions. See Figma screenshot for how it will work (updated designs in progress)
<details><summary>Figma Screenshot</summary>
<p>

![Create Project 04](https://github.com/hackforla/VRMS/assets/134463646/4dd751a0-1346-4f2f-ac59-1e7e8f0d4e1b)

</p>
</details>

**Comment by juliagab56** [comment] 2023-06-24 19:32
@heyitsalexander If you had time, could you give a bit more context as to what we need here? Is this a need for both UX and devs? I remember this ask but not sure at what stage this issue is right now. Thank you!

**Comment by heyitsalexander** [comment] 2023-06-26 18:15
@juliagab56 this was a feature request from Bonnie that I capture on this ticket. We never had a chance to actually do any discovery work on this or flesh it out. I would follow up with Bonnie and see how important this is. It doesn't sounds like this was a priority anymore given the new direction we were given.

**Comment by juliagab56** [comment] 2023-07-05 19:17
@ExperimentsInHonesty would love an update on this. Are you currently able to assign PMs to a project through VRMS or is this still a backend process?

**Comment by juliagab56** [comment] 2023-07-24 18:00
@JackHaeg not sure if this is still relevant or it's resolved? It's also missing a lot of specs. Issue needs to be re-written.

**Comment by juliagab56** [comment] 2023-11-28 18:49
Issue is still missing specs and there are two issues related to this.

**Comment by juliagab56** [comment] 2024-03-26 02:39
- This is a duplicate of, #1243

**Closed as not planned by juliagab56** 2024-03-26 02:39 UTC
Labels: role: UI/UX design, size: 1pt, p-feature: Project Details, p-feature: User Permissions, complexity: missing
