### ISSUE TITLE
PMs need to be able to give other PMs access

### ISSUE THREAD

**Issue by Steph112792** [hackforla/VRMS#1243] opened 2022-11-17 02:35 UTC
Overview 
There isn't a way for PM's to give other PM's access. New PM's do not have the ability to add/edit projects. This is a high priority as new PMs join the team and as others transition. New PM's will need access to finish or add to existing projects. 

Action Items
- [ ]  Give new PM's admin level access according to permissions from Bonnie
- [ ]  Access should be PM level access: Edit/Add projects

Acceptance Criteria
Scenario: New PMs are looking to add/edit new or existing projects in the portal
GIVEN: User wants to add a new project or edit an existing one; User is new to the team.
WHEN: User is trying to access the admin portal they do not have access
THEN: Permissions should be granted to User according to title but should not exceed Bonnie's access
AND: New PM's should be granted access when placed in on a project and denied access when no longer active

Resources/Instructions
Video Link:

Issue Time Stamp: Between 27:15-END - Not tested but Bonnie would like to test this first before PMs on the team

- #1273

-------------

# Overview
Issue: Project managers are only assignable by Admin level users at the moment.

Bonnie does not want to add and remove project admin herself. She is currently the only person who can add and remove project admin. we need to give project admin the ability to add and remove project admin from the project they have admin permissions on.
That way PM's can do all the work and not bonnie

### Goal
- [ ] PM can assign and remove PMs from projects they manage
- [ ] PM can add an event 
- [ ] PM can edit eventime 
- [ ] PM can see who else is assigned PM

### Icebox
- [ ] PM can unassign themselves
  - [ ] Modal popup warning no going back oh no!

#### Dev Ops
- [ ] Create feature branch for this issue
- [ ] Explore using a ref to grab  user/project management info OR
  - [ ] requires database migration

#### Backend
- [ ] Update database to populate managedByUsers array
- [ ] Create controller that will update managedByUser field in the projects model
- [ ] Update user controller to update projects model as well

#### Frontend
- [ ] Display managedByUsers on project page
- [ ] Create interface where PM or Admin can add users as Project Managers to the Project Page
  - [ ] Seach bar
  - [ ] User information
  - [ ] Trash button
    - [ ] Modal: Do you really want to remove this user?
    - [ ] !

#### Wrap Up
- [ ] Enjoy Old Fashioned because we did a good job

**Comment by JackHaeg** [comment] 2024-08-13 01:47
@juliagab56 un-assigned this issue for now as it is in the prioritized backlog (per Bonnie: only issues that are "in progress", or are marked as a "draft" and being written up in the "New Issue Approval" column can be assigned).

**Comment by JackHaeg** [comment] 2024-09-05 22:23
- Closing issue as it is a duplicate of #1231

**Closed as not planned by JackHaeg** 2024-09-05 22:23 UTC
Labels: role: Database, ready for dev lead, size: 2pt, p-feature: Project Details, p-feature: User Permissions, complexity: missing
