### ISSUE TITLE
User can type text into GitHub handle field

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1179] opened 2022-08-05 02:39 UTC

**Comment by JackHaeg** [comment] 2023-07-21 00:22
Evaluate if this is a duplicate of another issue, or if it needs to be rewritten.

**Comment by JackHaeg** [comment] 2023-07-21 00:24
@heyitsalexander Hi Alex, did you mean to make this a separate issue for #1174? If not, can we remove / close this issue?

**Comment by JackHaeg** [comment] 2023-07-21 03:21
Closing issue per discussion with Alex.

**Closed as completed by JackHaeg** 2023-07-21 03:21 UTC
Labels: role: Front End, role: Back End, p-feature: Login, ready for product manager, size: 1pt, complexity: missing
