### ISSUE TITLE
As a Project Level Admin, I need to be able to create and edit meeting times, so that I can keep HackforLA events page up-to-date.

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1178] opened 2022-08-05 02:27 UTC
### Overview
As a Project Level Admin, I need to be able to create and edit meeting times, so that I can keep HackforLA events page up-to-date.

### Acceptance Criteria

- [ ] New user can create an account
- [ ] Returning user can enter login and password or email link (?)
- [ ] User can create new meeting times for projects they are assigned to as admins
- [ ] User can edit meeting times for projects they are assigned to as admins
- [ ] Updated meeting times are updated on HackforLA website

### Action Items
- [x] #1183
- [x] #1184

### Resources/Instructions
- [ ] Link to Figma

Questions:
- [ ] Decide how can we're going to HforLA website will continue to pull from the VRMS API?

**Comment by ExperimentsInHonesty** [comment] 2023-03-10 20:16
The comments that follow are from the pms who tried to do this

**Comment by priyatalwar** [comment] 2023-03-10 20:17
Test: Priyanka @ Tech Work experience got the magic link and was able to log in right away 
 -  Meeting details were not there so I went to "Create New Event" and manually entered the details to create new events
 - Events were created right away
 -  All meetings have been successfully added

**Comment by Rabia2219** [comment] 2023-03-10 20:17
Rabia Shaikh - YJN
- received the magic link after over 1 minute
- the updates were reflected right away
- if a value is added in the DESCRIPTION during the 1st update but then left empty in the following updates, it auto displays the last value

**Comment by allthatyazz** [comment] 2023-03-10 20:18
Yasaman Roostaeian - Design Systems 
My email was not recognized. "We don’t recognize your email address. Please, create an account." Bonnie has confirmed the email I am using for the login is the same one recorded in the VRMS admin pannel. 

![image](https://user-images.githubusercontent.com/100178353/224425923-30030442-d7c2-4310-9cb5-2b39bb737ed7.png)

**Comment by kcoronel** [comment] 2023-03-10 20:18
I was able to sign-in, but it took me a couple of tries. The first time I received the magic link, it told me the link was invalid (Sorry, the link is not valid anymore.), the second time the magic link worked.

**Comment by seannwvong** [comment] 2023-03-10 20:18
Test for shawn.wong@gmail.com: You don't have the correct access level to view the dashboard

Update: Bonnie added me and assigned me to the Guides project, can view it now. Issue is Resolved

**Comment by mojimoh** [comment] 2023-03-10 20:20
Test for moji.jimoh@gmail.com: initial attempt to log-in was unsuccessful "We don't recognize your email address. Please, create an account", Closed tab and on 2nd attempt recognized received a magic link.
Was successful in updating existing events and add a new event. using Microsoft edge browser.

**Comment by allthatyazz** [comment] 2023-03-10 20:39
We noticed that meetings with .5 duration cannot be saved properly. 

Other updates from Zoom chat: 
- Karen at 12:32 "I have to jump, but it gave me a server error this last time I tried." 
- Salima at 12:35 "I’m trying to remove the word Meeting in the CTJ meetings and when I click Update it says Invalid Link."

**Comment by jamiesiu** [comment] 2023-03-10 20:44
Able to log in and make changes for Expunge Assist. +1 to comments that .5 duration causes issues with being able to make updates

**Comment by rpradheap** [comment] 2023-03-10 20:56
I was able to update the product meeting for Home Unite US. Please note I wasn't able to update the Team meeting and then Bonnie was able to update it. Later it was found the issue was that the VRMS application is not updating when the meeting is only for 30 minutes.

**Comment by ExperimentsInHonesty** [comment] 2023-03-11 15:40
Meetings that are currently scheduled for 30 min, or new meetings that are 30 min, have to be changed to 1 hour.  Then you can save.  After saving, you can go back and make that one change.  So we think that its the combination of changes that is the problem.

**Comment by itserindean** [comment] 2023-03-22 20:20
Can you you assign permissions to me for FOLA to change meeting times in vrms?

**Comment by jbubar** [comment] 2023-06-27 02:39
Closing this issue because we have completed this feature

**Closed as completed by jbubar** 2023-06-27 02:39 UTC
Labels: role: Product, size: missing, p-feature: Events, User Story 1: create + edit meeting times, milestone: missing, complexity: missing
