### ISSUE TITLE
Bug: Backend is creating duplicates for event checkins

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1424] opened 2023-07-14 21:32 UTC
### Overview
We need to fix the meeting check in dropdown options to only show a single instance of an event so that users are not trying to check into different instances of the same event, or be confused.  

#### Details: 
Both dev and prod are creating duplicate events for weekly checkins. 

<details>
<summary>Screenshots</summary>

## dev

![image](https://github.com/hackforla/VRMS/assets/5898009/21b12988-7e0c-47d4-8ffb-88894454142c)

## prod

![image](https://github.com/hackforla/VRMS/assets/5898009/8aeb087d-c0f7-4344-991b-82e287d6db65)

</summary>
</details>

<details>
<summary>Stringified event object from Frontend Friday, 1:45ish</summary>

```js
/* Array received by frontend */

[ 
      {
        "location": {
          "city": "Los Angeles",
      "state": "CA",
      "country": "USA"
    },
    "checkInReady": true,
    "_id": "64b1a9417f0534612ad558ff",
    "name": "OnboardingTestFriday",
    "hacknight": "Online",
    "eventType": "Onboarding",
    "project": {
          "recruitingCategories": [],
      "partners": [],
      "managedByUsers": [],
      "_id": "6453dfff390bc1002ab3eb6d",
      "name": "! Test--event-1:30pm",
      "description": "CHANGEd",
      "location": "BLOCK",
      "githubUrl": "https://github.com/aave",
      "slackUrl": "asdf",
      "googleDriveUrl": "asdfeeddaasaaaaaaa",
      "projectStatus": "Active",
      "createdDate": "2023-05-04T16:40:31.024Z",
      "__v": 0,
      "hflaWebsiteUrl": "!!! AAVEaaaaaaa"
    },
    "date": "2023-07-14T20:30:00.809Z",
    "startTime": "2023-07-14T20:30:00.809Z",
    "endTime": "2023-07-14T22:30:00.809Z",
    "hours": 2,
    "createdDate": "2023-07-14T20:00:01.500Z",
    "updatedDate": "2023-07-14T20:00:01.500Z",
    "__v": 0
  },
  {
        "location": {
          "city": "Los Angeles",
      "state": "CA",
      "country": "USA"
    },
    "checkInReady": true,
    "_id": "64b1a94503228e0020f67576",
    "name": "OnboardingTestFriday",
    "hacknight": "Online",
    "eventType": "Onboarding",
    "project": {
          "recruitingCategories": [],
      "partners": [],
      "managedByUsers": [],
      "_id": "6453dfff390bc1002ab3eb6d",
      "name": "! Test--event-1:30pm",
      "description": "CHANGEd",
      "location": "BLOCK",
      "githubUrl": "https://github.com/aave",
      "slackUrl": "asdf",
      "googleDriveUrl": "asdfeeddaasaaaaaaa",
      "projectStatus": "Active",
      "createdDate": "2023-05-04T16:40:31.024Z",
      "__v": 0,
      "hflaWebsiteUrl": "!!! AAVEaaaaaaa"
    },
    "date": "2023-07-14T20:30:00.809Z",
    "startTime": "2023-07-14T20:30:00.809Z",
    "endTime": "2023-07-14T22:30:00.809Z",
    "hours": 2,
    "createdDate": "2023-07-14T20:00:05.618Z",
    "updatedDate": "2023-07-14T20:00:05.618Z",
    "__v": 0
  }
]
```

</details>

### Action Items
 - [ ] Go through the backend and figure out why events are being created twice.
 - [ ] Fix it!
 - [ ] Confirm it's fixed and create test files to ensure it doesn't break again.

**Comment by bkmorgan3** [comment] 2023-07-29 05:30
@Spiteless  
I don't know who else to ask but can I get some clarity on how to reproduce this? 
What kind of user should I be using?
What route do I hit ?

Can you give me some steps to reproduce this?

**Comment by trillium** [comment] 2023-07-31 23:51
@bkmorgan3 
I wish I could give you more direction on how to reproduce this, but honestly I don't know what's going on to produce this bug. My suggestion for how to investigate and reproduce ~:

 * query db for events, see where duplicates exist
 * Look at similar properties of these duplicates to gauge what data is triggering a duplicate generation
   * Might only be timestamps, I'm not totally sure here
 * Create unit tests for workers that create the events and pass them to the db
 * Try to find a sequence of test data where the unit tests produce duplicates

That's how I'd start on this, please let me know how progress is coming along here.

**Comment by bkmorgan3** [comment] 2023-08-07 19:03
@Spiteless   @JackHaeg 
Is this still an active issue?  I cant reproduce it

**Comment by JackHaeg** [comment] 2023-10-24 02:24
Closing as solved.

**Closed as completed by JackHaeg** 2023-10-24 02:24 UTC
Labels: role: Back End, Bug, time-sensitive, feature: Database, size: 2pt, complexity: missing
